# Generated by Django 4.0.6 on 2022-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
