# Generated by Django 4.0.6 on 2022-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
