# Generated by Django 4.0.6 on 2022-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_person_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partners',
        ),
        migrations.AddField(
            model_name='person',
            name='partners',
            field=models.ManyToManyField(to='home.partners'),
        ),
    ]
