# Generated by Django 4.0.6 on 2022-07-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_person_partners_person_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
