# Generated by Django 4.0.6 on 2022-07-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_partners_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=models.ImageField(blank=True, upload_to='awards'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, upload_to='education'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, upload_to='experience'),
        ),
    ]
