# Generated by Django 4.0.6 on 2022-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_education_place_alter_awards_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
