# Generated by Django 4.0.6 on 2022-07-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_experience_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
