# Generated by Django 4.0.6 on 2022-07-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_awards_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='ico',
            field=models.ImageField(blank=True, upload_to='services'),
        ),
        migrations.AddField(
            model_name='services',
            name='text_ico',
            field=models.ManyToManyField(to='home.servicestext'),
        ),
    ]
