# Generated by Django 4.0.6 on 2022-07-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_servicestext_alter_services_ico_services_text_ico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='text_ico',
        ),
        migrations.AddField(
            model_name='services',
            name='text_ico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.servicestext'),
        ),
    ]
