# Generated by Django 4.0.6 on 2022-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_services_text_ico_services_text_ico'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
