# Generated by Django 4.0.6 on 2022-07-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_projects_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='another',
            name='available',
        ),
        migrations.RemoveField(
            model_name='another',
            name='sub_available',
        ),
    ]
