# Generated by Django 4.0.6 on 2022-07-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_another_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='media',
            new_name='image',
        ),
    ]
